import React, { useCallback, useState } from 'react'
import { Loader, Card, FormFeild } from '../components'

const Home = () => {
  const [Loading, setLoading] = useState(false)
  const [allPost, setAlllPosts] = useState(null)
  const [searchText, setSearchText] = useState(null)

  const RenderCards = useCallback(({ data, title }) => {
    if (data?.length > 0) {
      return data.map((post) => <Card key={post._id} {...post} />)
    }

    return <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase' >{title}</h2>
  }, [])

  return (
    <section className='max-w-7x1 mx-auto' >
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]' >
          The Community Showcase
        </h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px]'>
          Browse through a collection of imaginative and visually stunning images generated by DALL-E AI
        </p>
      </div>

      <div className="mt-16">
        <FormFeild />
      </div>

      <div className="mt-10">
        {
          Loading ? (
            <div className='flex justify-center items-center' >
              <Loader />
            </div>
          ) : (
            <>
              {
                searchText && (
                  <h2 className='font-medium text-[#666e75] text-xl mb-3' >
                    Showing  results for <span className='text-[#222328]' >{searchText}</span>
                  </h2>
                )
              }

              <div className='grid lg-grid-cols-4 sm:grid-cols-3 xl:grid-cols-2 
              grid-cols-1 gap-3' >
                {
                  searchText ? (
                    <RenderCards
                      data={[]}
                      title={"No search results"}
                    />
                  ) : (
                    <RenderCards
                      data={allPost}
                      title={"No posts found"}
                    />
                  )
                }
              </div>
            </>
          )
        }
      </div>
    </section>
  )
}

export default Home